export const routes = {
  home: '/',
  authHome: '/home',
  register: '/register',
  signIn: '/signin',
  verification: '/verification/otp',
  settings: {
    home: '/settings',
    notification: '/settings/notifications',
    helpCenter: '/settings/help-center',
  },
  user: {
    profile: 'user/profile',
  },
  // signIn: '/user/signin',
  forgetPassword: '/user/forget-password',
  adminLogin: '/super-admin/login',
  dashboard: '/super-admin/dashboard',
  questionsBank: {
    home: '/super-admin/questions-bank',
    create: '/super-admin/questions-bank/create',
    edit: (id: string) => `/super-admin/questions-bank/update/${id}`,
  },
  dailyQuizzes: {
    home: '/super-admin/daily-quizzes',
    create: '/super-admin/daily-quizzes/create',
    edit: (id: string) => `/super-admin/daily-quizzes/update/${id}`,
  },
  liveQuizzes: {
    home: '/super-admin/live-quizzes',
    create: '/super-admin/live-quizzes/create',
    edit: (id: string) => `/super-admin/live-quizzes/update/${id}`,
  },
  reports: {
    dailyQuiz: '/super-admin/reports/daily-quiz',
    liveQuiz: '/super-admin/reports/live-quiz',
  },
  faqs: {
    home: '/super-admin/faqs',
    create: '/super-admin/faqs/create',
    edit: (id: string) => `/super-admin/faqs/update/${id}`,
  },
  upcomingFeatures: {
    home: '/super-admin/upcoming-features',
    create: '/super-admin/upcoming-features/create',
    edit: (id: string) => `/super-admin/upcoming-features/update/${id}`,
  },
  notifications: {
    home: '/super-admin/notifications',
    create: '/super-admin/notifications/create',
    edit: (id: string) => `/super-admin/notifications/update/${id}`,
  },
  manageUsers: {
    home: '/super-admin/manage-users',
    create: '/super-admin/manage-users/create',
    edit: (id: string) => `/super-admin/manage-users/update/${id}`,
  },
  manageAdmins: {
    home: '/super-admin/manage-admins',
    create: '/super-admin/manage-admins/create',
    edit: (id: string) => `/super-admin/manage-admins/update/${id}`,
  },
  deleteAccounts: '/super-admin/delete-accounts',
  generalSettings: '/super-admin/general-settings',

  // Skip others routes for now...

  manageLive: {
    home: '/super-admin/manage-live-matches',
    create: '/super-admin/manage-live-matches/create',
    details: (id: string) => `/super-admin/manage-live-matches/${id}`,
    edit: (id: number) => `/super-admin/manage-live-matches/update/${id}`,
  },
  fixture: {
    football: '/super-admin/fixtures/football',
    cricket: '/super-admin/fixtures/cricket',
  },
  highlights: {
    football: {
      home: '/super-admin/highlights/football',
      create: '/super-admin/highlights/football/create',
      details: (id: string) => `/super-admin/highlights/football/${id}`,
      edit: (id: string) => `/super-admin/highlights/football/update/${id}`,
    },
    cricket: {
      home: '/super-admin/highlights/cricket',
      create: '/super-admin/highlights/cricket/create',
      details: (id: string) => `/super-admin/highlights/cricket/${id}`,
      edit: (id: string) => `/super-admin/highlights/cricket/update/${id}`,
    },
  },
  popularFootballEntity: '/super-admin/popular/football-entities',
  popularCricketEntity: '/super-admin/popular/cricket-entities',
  eCommerce: {
    dashboard: '/ecommerce',
    products: '/ecommerce/products',
    createProduct: '/ecommerce/products/create',
    productDetails: (slug: string) => `/ecommerce/products/${slug}`,
    ediProduct: (slug: string) => `/ecommerce/products/${slug}/edit`,
    categories: '/ecommerce/categories',
    createCategory: '/ecommerce/categories/create',
    editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
    orders: '/ecommerce/orders',
    createOrder: '/ecommerce/orders/create',
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: '/ecommerce/reviews',
    shop: '/ecommerce/shop',
    cart: '/ecommerce/cart',
    checkout: '/ecommerce/checkout',
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  searchAndFilter: {
    realEstate: '/search/real-estate',
    nft: '/search/nft',
    flight: '/search/flight',
  },
  support: {
    dashboard: '/support',
    inbox: '/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/support/snippets',
    createSnippet: '/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/support/templates',
    createTemplate: '/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  logistics: {
    dashboard: '/logistics',
    shipmentList: '/logistics/shipments',
    customerProfile: '/logistics/customer-profile',
    createShipment: '/logistics/shipments/create',
    editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  executive: {
    dashboard: '/executive',
  },
  analytics: '/analytics',
  file: {
    dashboard: '/file',
    manager: '/file-manager',
    upload: '/file-manager/upload',
    create: '/file-manager/create',
  },
  pos: {
    index: '/point-of-sale',
  },
  eventCalendar: '/event-calendar',
  rolesPermissions: '/roles-permissions',
  invoice: {
    home: '/invoice',
    create: '/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
  },
  widgets: {
    cards: '/widgets/cards',
    icons: '/widgets/icons',
    charts: '/widgets/charts',
    maps: '/widgets/maps',
    banners: '/widgets/banners',
  },
  tables: {
    basic: '/tables/basic',
    collapsible: '/tables/collapsible',
    enhanced: '/tables/enhanced',
    pagination: '/tables/pagination',
    search: '/tables/search',
    stickyHeader: '/tables/sticky-header',
  },
  multiStep: '/multi-step',
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  emailTemplates: '/email-templates',
  profile: '/profile',
  welcome: '/welcome',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp1: '/auth/sign-up-1',
    signUp2: '/auth/sign-up-2',
    signUp3: '/auth/sign-up-3',
    signUp4: '/auth/sign-up-4',
    signUp5: '/auth/sign-up-5',
    // sign in
    signIn1: '/auth/sign-in-1',
    signIn2: '/auth/sign-in-2',
    signIn3: '/auth/sign-in-3',
    signIn4: '/auth/sign-in-4',
    signIn5: '/auth/sign-in-5',
    // forgot password
    forgotPassword1: '/auth/forgot-password-1',
    forgotPassword2: '/auth/forgot-password-2',
    forgotPassword3: '/auth/forgot-password-3',
    forgotPassword4: '/auth/forgot-password-4',
    forgotPassword5: '/auth/forgot-password-5',
    // OTP
    otp1: '/auth/otp-1',
    otp2: '/auth/otp-2',
    otp3: '/auth/otp-3',
    otp4: '/auth/otp-4',
    otp5: '/auth/otp-5',
  },
};
